---
- name: Install unzip utility
  apt:
    name: unzip
    state: present

- name: Download Bezu binaries
  unarchive:
    src: "{{ bezu_url }}"
    remote_src: yes
    creates: "/home/{{ ansible_user }}/besu-22.1.3"
    dest: "/home/{{ ansible_user }}"
    mode: 0755

- name: Create alias bin in /usr/local/bin
  file:
    state: link
    src: "/home/{{ ansible_user }}/besu-22.1.3/bin/besu"
    dest: /usr/local/bin/besu
    mode: 0755
