---
- name: Install unzip utility
  apt:
    name: unzip
    state: present

- name: Download  binaries
  unarchive:
    src: "{{ teku_url }}"
    remote_src: yes
    creates: "/home/{{ ansible_user }}/teku-22.4.0"
    dest: "/home/{{ ansible_user }}"
    mode: 0755

- name: Create alias bin in /usr/local/bin
  file:
    state: link
    src: "/home/{{ ansible_user }}/teku-22.4.0/bin/teku"
    dest: /usr/local/bin/teku
    mode: 0755

- name: Create data dir
  file:
    path: /home/{{ ansible_user }}/tekudata
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Create config file
  template:
    src: teku.config.yml
    dest: "/home/{{ ansible_user }}/teku.config.yml"
  notify: restart teku

- name: Create jwt secret file
  template:
    src: jwtsecret.hex
    dest: "/home/{{ ansible_user }}/jwtsecret.hex"
  notify: restart teku

- name: Create service file
  template:
    src: teku.service
    dest: "/etc/systemd/system/teku.service"
  notify: restart teku

- name: Enable service
  systemd:
    name: teku
    daemon_reload: yes
    enabled: true
