---

- hosts: all
  become: yes
  tasks:
    - name: Change ssh server port
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Port'
        line: "Port {{ ssh_port }}"
    - name: Restart sshd
      service:
        name: sshd
        state: restarted
