---
- name: Install unzip utility
  apt:
    name: unzip
    state: present

- name: Download Besu binaries
  unarchive:
    src: "{{ besu_url }}"
    remote_src: yes
    creates: "/home/{{ ansible_user }}/besu-22.1.3"
    dest: "/home/{{ ansible_user }}"
    mode: 0755

- name: Create alias bin in /usr/local/bin
  file:
    state: link
    src: "/home/{{ ansible_user }}/besu-22.1.3/bin/besu"
    dest: /usr/local/bin/besu
    mode: 0755

- name: Create data dir
  file:
    path: /home/{{ ansible_user }}/besudata
    state: directory
    mode: 0755

- name: Create config file
  template:
    src: besu.config.toml
    dest: "/home/{{ ansible_user }}/besu.config.toml"
  notify: restart besu

- name: Create jwt secret file
  template:
    src: jwtsecret.hex
    dest: "/home/{{ ansible_user }}/jwtsecret.hex"
  notify: restart besu

- name: Create service file
  template:
    src: besu.service
    dest: "/etc/systemd/system/besu.service"
  notify: restart besu

- name: Enable service
  systemd:
    name: besu
    daemon_reload: yes
    enabled: true
